FROM node:23.5-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

RUN apk add --no-cache dos2unix

COPY . .

RUN dos2unix startup.sh && chmod +x startup.sh

CMD ["/bin/sh", "./startup.sh"]
