services:
  amazn_db:
    image: postgres:latest
    container_name: amazn_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=amazndb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db_data:/var/lib/postgresql/data 

volumes:
  db_data: